import './globals.css'
import './typography.css'

import { Roboto } from 'next/font/google'


const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "300", "500", "700", "900"],
  style: ["italic", "normal"],
  variable: "--font-roboto",
})

import Providers from '@/contexts/Providers'

export const metadata = {
  title: 'Huann Vicente Portifolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body data-scroll className={`${roboto.variable} pointer-events-none font-roboto h-screen overflow-x-hidden w-screen bg-black selection:bg-green-200 selection:text-lightPrimary`}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html >
  )
}
